name: yimby
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi=0.104.1
  - uvicorn=0.24.0
  - geopandas=0.14.1
  - shapely=2.0.2
  - python-dotenv=1.0.0
  - pip
  - pip:
    - python-multipart